spring.application.name=saucedemo
server.port=8080

# Conexion a Neon (PostgreSQL)
# Reemplaza TU_PASSWORD por la password real de tu proyecto Neon (boton "Show password")
spring.datasource.url=jdbc:postgresql://ep-red-block-ayfuz330.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3OERm5xXcNdJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
